In [1]:
!python -V

Python 3.9.18


In [3]:
import pandas as pd

In [3]:
pd.__version__

'2.0.3'

In [4]:
import numpy as np

## Arrays

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.full(10,1.5)

array([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5])

In [17]:
a = np.array([1,2,3,5,7,12])

In [18]:
a

array([ 1,  2,  3,  5,  7, 12])

In [19]:
a[2]

3

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [4]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
n = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

In [9]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
n[0]

array([1, 2, 3])

In [12]:
n[:,2]

array([3, 6, 9])

In [14]:
np.random.rand(5,2)

array([[0.1383289 , 0.9229207 ],
       [0.93032335, 0.98552383],
       [0.52594018, 0.14489488],
       [0.9945398 , 0.23914972],
       [0.48821927, 0.48231226]])

In [17]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [18]:
np.random.seed(10)
np.random.randn(5,2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [19]:
np.random.seed(10)
100*np.random.rand(5,2)

array([[77.13206433,  2.07519494],
       [63.36482349, 74.88038825],
       [49.85070123, 22.47966455],
       [19.80628648, 76.05307122],
       [16.91108366,  8.83398142]])

In [21]:
np.random.seed(10)
np.random.randint(low=0, high=100, size=(5,2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

In [40]:
a = np.arange(5)

In [41]:
a = a*2

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [42]:
b = np.arange(5)

In [43]:
a > b

array([False,  True,  True,  True,  True])

In [44]:
a.min()

0

In [45]:
a.max()

8

In [47]:
a.mean()

4.0

In [48]:
a.sum()

20

In [49]:
a.std()

2.8284271247461903

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-17 17:55:33--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.1s    

2023-09-17 17:55:33 (13.4 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [ ]:
pd.read_csv('housing.csv')

In [5]:
df = pd.read_csv('housing.csv')


In [6]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [33]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [12]:
df['ocean_proximity'].nunique()

5

In [13]:
df.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [20]:
df_new = df[
    df['ocean_proximity'] == 'NEAR BAY'
  ]

In [21]:
df_new

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
19067    -122.45     38.28                20.0       3306.0           503.0   
19068    -122.47     38.29                14.0       3732.0           846.0   
19069    -122.45     38.27                25.0       5024.0           881.0   
19077    -122.49     38.27                 8.0       5092.0           988.0   
19104    -122.51     38.17                 8.0       5875.0          1115.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
19067      1374.0       460.0         5.7984            297600.0   
19068      1277.0       775.0         2.5658            208000.0   
19069      1994.0       838.0         4.2237            262300.0   
19077      1657.0       936.0         3.5625            213200.0   
19104      2808.0      1029.0         3.6392            246300.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
19067        NEAR BAY  
19068        NEAR BAY  
19069        NEAR BAY  
19077        NEAR BAY  
19104        NEAR BAY  

[2290 rows x 10 columns]

In [22]:
df_new.median_house_value.mean()

259212.31179039303

In [23]:
df_new.describe()

longitude     latitude  housing_median_age   total_rooms  \
count  2290.000000  2290.000000         2290.000000   2290.000000   
mean   -122.260694    37.801057           37.730131   2493.589520   
std       0.147004     0.185434           13.070385   1830.817022   
min    -122.590000    37.350000            2.000000      8.000000   
25%    -122.410000    37.730000           29.000000   1431.250000   
50%    -122.250000    37.790000           39.000000   2083.000000   
75%    -122.140000    37.907500           52.000000   3029.750000   
max    -122.010000    38.340000           52.000000  18634.000000   

       total_bedrooms   population   households  median_income  \
count     2270.000000  2290.000000  2290.000000    2290.000000   
mean       514.182819  1230.317467   488.616157       4.172885   
std        367.887605   885.899035   350.598369       2.017427   
min          1.000000     8.000000     1.000000       0.499900   
25%        289.000000   718.250000   275.000000       2.834750   
50%        423.000000  1033.500000   406.000000       3.818650   
75%        628.750000  1495.000000   599.250000       5.054425   
max       3226.000000  8276.000000  3589.000000      15.000100   

       median_house_value  
count         2290.000000  
mean        259212.311790  
std         122818.537064  
min          22500.000000  
25%         162500.000000  
50%         233800.000000  
75%         345700.000000  
max         500001.000000

In [24]:
df_new.total_bedrooms.mean()

514.1828193832599

In [34]:
df.total_bedrooms.mean()

537.8705525375618

In [35]:
df['total_bedrooms'] = df.total_bedrooms.fillna(537)

In [36]:
df.total_bedrooms.mean()

537.8618217054263

In [37]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [39]:
df['ocean_proximity'].nunique()

5

In [40]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20640.000000  20640.000000  20640.000000   20640.000000   
mean       537.861822   1425.476744    499.539680       3.870671   
std        419.266601   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    787.000000    280.000000       2.563400   
50%        438.000000   1166.000000    409.000000       3.534800   
75%        643.250000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [41]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [37]:
df_prob7 = df[ df['ocean_proximity'] == 'ISLAND']

In [38]:
df_prob7

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [39]:
X = df_prob7[['housing_median_age','total_rooms','total_bedrooms']].values

In [40]:
X = np.array(df_prob7[['housing_median_age','total_rooms','total_bedrooms']].values)

In [41]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [12]:
XT= X.transpose()

In [24]:
XTX = np.dot(XT,X)

In [25]:
XTX
    
    

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [35]:
y = np.array([950, 1300, 800, 1000, 1300])

In [42]:
XTXT = np.linalg.inv(XTXT)

In [43]:
XTXT

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [44]:
X_N = np.dot(XTXT,XT)
X_N

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [46]:
w = X_N.dot(y)

In [47]:
w

array([23.12330961, -1.48124183,  5.69922946])